title: otávio mk
# email: email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  otávio manzano kavakama - cello
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://otaviomk.com" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap
  # - jekyll-paginate-v2

# Paginate
# permalink: /:year/:month/
# pagination:
#   enabled: true
#   per_page: 5
#   sort_reverse: true
#   sort_field: 'date'
#   title: ':title'
#   trail:
#     before: 2
#     after: 2

# Conversion
markdown:    kramdown
highlighter: rouge

# Markdown Processors
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge

header_pages:
  - about.markdown
  - media.md
  - works.md
  - contact.md

twitter_username: kavotaman
facebook_username: kavotaman
instagram_username: kavotaman
# youtube_username: jekyll
# googleplus_username: +jekyll

exclude:
  - "Gemfile"
  - "clean-theme.gemspec"
  - "Gemfile.lock"
  - "vendor/bundle/"
  - "vendor/cache/"
  - "vendor/gems/"
  - "vendor/ruby/"
  - "br"
